# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordposition',
            name='position',
        ),
        migrations.AddField(
            model_name='wordposition',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
    ]
